---
title: "Surveyfreq"
output: word_document
---



## R Markdown


```{r}
library(haven)
me0015_m <- read_sas("//Users/mikelapika/Desktop/me0015_m.sas7bdat")
tempdataset <- me0015_m
 
```

```{r}
#Load data from 2015 only
# with dplyr
tempdataset2 = dplyr::filter(me0015_m, year == '2015')
tempdataset2


```
```{r}

#Format data general health
tempdataset2$genhlth_f <- factor(tempdataset2$GENHLTH, levels=c(1, 2, 3, 4,5,7,9),labels=c("Excellent", "Very good", "Good","Fair","Poor","Don’t know/Not sure","Refused"))

# Format data county
tempdataset2$cty_f <- factor(tempdataset2$county, levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),labels=c("Androscoggin", "Aroostook", "Cumberland","Franklin","Hancock","Kennebec","Knox","Lincoln","Oxford","Penobscot","Piscataquis","Sagadahoc","Somerset","Waldo","Washington","York"))

# Format Gender

tempdataset2$sex_f <- factor(tempdataset2$SEX, levels=c(1, 2),labels=c("Male", "Female"))

# Format Age

tempdataset2$age_f <- factor(tempdataset2$`_AGEG5YR`, levels=c(1, 2, 3, 4,5,6,7,8,9,10,11,12,13,14),labels=c("18-24", "25-29", "30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80+","Refused"))




```


```{r}
library(gmodels)
table(tempdataset2$genhlth_f, useNA="ifany")
```

```{r}

table(tempdataset2$genhlth_f, tempdataset2$Part)
```

```{r}
#Crosstable Frequency
CrossTable(tempdataset2$genhlth_f, tempdataset2$Part,useNA="ifany")
```
```{r}
#Summary tools
library(summarytools)
dfSummary(tempdataset2$genhlth_f, style = "grid", plain.ascii = TRUE)


```


```{r}
# Survey Means
library(foreign)
library(survey)
#mydesign <- svydesign(id = ~1, strata = ~`_STSTR` ,data = tempdataset2 ,	weight = ~`_LLCPWT` ,cluster= ~`_psu`)
mydesign <- svydesign(id = ~`_psu`, strata = ~`_STSTR` ,	weight = ~`_LLCPWT`,data = tempdataset2, nest = TRUE )
svymean(~genhlth_f,mydesign)



```




```{r}
# Survey Total
library(foreign)
library(survey)
library(grid)
library(Matrix)
library(survival)
mydesign <- svydesign(id = ~`_psu`, strata = ~`_STSTR` ,	weight = ~`_LLCPWT`,data = tempdataset2, nest = TRUE )
#svyby(~genhlth_f,~Part,design=mydesign)

svytotal(~genhlth_f,mydesign,deff=T)
confint(svytotal(~genhlth_f, mydesign))

# surbeyby
ex53 <- svyby (~genhlth_f, ~cty_f, mydesign, svymean, deff=T)
ex53
```
```{r}

library(summarytools)
freq(tempdataset2$genhlth_f)


```






```{r}
#select variable to use
meps06 <- subset(tempdataset2,select = c(`_STSTR`, `_LLCPWT`, `_psu`, `GENHLTH`,`_AGEG5YR`, `year`, `county`, `SEX`))
```



```{r}
mydesign <- svydesign(id = ~`_psu`, strata = ~`_STSTR` ,	weight = ~`_LLCPWT`,data = tempdataset2, nest = TRUE )

svytotal(~genhlth_f,mydesign)

svyby( ~genhlth_f , ~cty_f , mydesign , svytotal )
#class(mydesign)

```



```{r}
svyby( 
	~GENHLTH , 
		~genhlth_f+~cty_f ,
	mydesign ,
	svymean  
)
```


```{r}
mydesign <- svydesign(id = ~`_psu`, strata = ~`_STSTR` ,	weight = ~`_LLCPWT`,data = tempdataset2, nest = TRUE )
#summary(mydesign)

#svytotal(~genhlth_f,mydesign)

#svyby( ~genhlth_f , ~cty_f , mydesign , svytotal )
#class(mydesign)

(tbl <- svytable(~genhlth_f, mydesign))
  svychisq(~genhlth_f, mydesign)
  summary(tbl, statistic="Chisq")
  svychisq(~genhlth_f, mydesign, statistic="adjWald")

```


```{r}

```


```{r}

```



```{r}

```



```{r}

```